
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainApplicationWindow.java
 *
 * Created on 29 Ιαν 2009, 4:05:19 μμ
 */
/**
 *
 * @author User
 */
public class MainApplicationWindow extends javax.swing.JFrame {

    //Το κύριο παράθυρο της εφαρμογής μας
    DoctorStuff doctorsRecords;

    //Απθήκευση της τρέχουσας κατάστασης στο αρχείο
    public void SaveStatus() {
        try {
            ObjectOutputStream fl = new ObjectOutputStream(new FileOutputStream("doctor.ser"));
            fl.writeObject(doctorsRecords);
            fl.close();

        } catch (IOException er) {
        }
    }

    //Ανάκτηση της κατάστασης από το αρχείο
    public void LoadStatus() {
        try {
            ObjectInputStream fl = new ObjectInputStream(new FileInputStream("doctor.ser"));
            try {
                doctorsRecords = (DoctorStuff) fl.readObject();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MyCalendarForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            fl.close();
        } catch (IOException er) {
            doctorsRecords = new DoctorStuff();
        }
    }

    public Patients getAllPatients() {
        return doctorsRecords.patients;
    }

    public void setAllPatients(Patients all) {
        doctorsRecords.patients = all;
    }

    /** Creates new form MainApplicationWindow */
    public MainApplicationWindow() {
        initComponents();
        LoadStatus();
        DynamicMenu();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiPanel = new javax.swing.JLayeredPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Διαχείριση Οφθαλμιατρείου");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mdiPanel.setAutoscrolls(true);
        mdiPanel.setFocusCycleRoot(true);
        mdiPanel.setFocusTraversalPolicyProvider(true);
        mdiPanel.setName("mdiPanel"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("Εφαρμογή");
        jMenu1.setName("jMenu1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Έξοδος");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ημερολόγιο");
        jMenu2.setName("jMenu2"); // NOI18N

        jMenuItem3.setText("Προβολή - Επεξεργασία");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.setRolloverEnabled(true);
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu4.setText("Εκτέλεση Ραντεβού");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Αρχείο Ασθενών");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Αναζήτηση με Φίλτρα");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Πληροφορίες Ασθενούς");
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked

    //Ο χρήστης ζητάει το ημερολόγιο
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MyCalendarForm frm = new MyCalendarForm(this);
        frm.setParentWindow(this);
        this.getMdiPanel().add(frm);
        frm.setVisible(true);
        this.repaint();
        frm.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //Ο χρήστης ζητάει τη βάση δεδομένων με τους ασθενείς
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        MyPatientsForm frm = new MyPatientsForm(this);
        this.getMdiPanel().add(frm);
        frm.setVisible(true);
        this.repaint();
        frm.repaint();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        DynamicMenu();



    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    //Όταν η εφαρμογή κλείνει, αποθηκεύουμε την κατάσταση
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        SaveStatus();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        SaveStatus();
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed
//Ο χρήστης θέλει να κάνει αναζήτηση
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SearchPatients newSearchForm = new SearchPatients();
        newSearchForm.setPatients(doctorsRecords.patients);
        newSearchForm.setVisible(true);
        this.getMdiPanel().add(newSearchForm);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //Η συνάρητησ αυτή δημιουργεί το δυναμικό μενού
    //με τα ραντεβού σε εκκρεμότητα. Με κλικ σε αυτά τα υπομενού αρχίζει η διαδικασία
    //της εξέτασης
    public void DynamicMenu() {
        jMenu4.removeAll();
        try {

            int currentElement = 0;
            Enumeration<Rendezvous> enmuRantevou = doctorsRecords.daybook.getRendezvous().elements();
            while (enmuRantevou.hasMoreElements()) {
                Rendezvous rendezvous = enmuRantevou.nextElement();
                if (rendezvous.isCompleted()) {
                    currentElement++;
                    continue;
                }
                String text = rendezvous.getPatient().getSurname() + ", " + rendezvous.getPatient().getName() + " - " +
                        rendezvous.getRandezvousDayTime().get(Calendar.DAY_OF_MONTH) + "/" + (1 + rendezvous.getRandezvousDayTime().get(Calendar.MONTH)) + " - " +
                        rendezvous.getRandezvousDayTime().get(Calendar.HOUR_OF_DAY) + ":" + (rendezvous.getRandezvousDayTime().get(Calendar.MINUTE));
                JMenuItem newMenuItem = new JMenuItem(text);
                newMenuItem.setMnemonic(currentElement);
                jMenu4.add(newMenuItem);
                newMenuItem.addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        MenuRantevouSelected((JMenuItem) e.getSource());
                    }
                });
                currentElement++;

            }
            this.repaint();
        } catch (Exception e) {
        }
    }

    public void MenuRantevouSelected(JMenuItem src) {
        int index = src.getMnemonic();
        Rendezvous randevou = doctorsRecords.daybook.getRendezvous().get(index);
        ExamsWindow examWindow = new ExamsWindow(this);
        examWindow.setExamDay(randevou.getRandezvousDayTime());
        examWindow.setPatient(randevou.getPatient());
        examWindow.setRendevousWorking(randevou);
        this.getMdiPanel().add(examWindow);
        examWindow.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainApplicationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLayeredPane mdiPanel;
    // End of variables declaration//GEN-END:variables
    private Vector<javax.swing.JMenuItem> mnuRantevou;

    /**
     * @return the mdiPanel
     */
    public javax.swing.JLayeredPane getMdiPanel() {
        return mdiPanel;
    }

    /**
     * @param mdiPanel the mdiPanel to set
     */
    public void setMdiPanel(javax.swing.JLayeredPane mdiPanel) {
        this.mdiPanel = mdiPanel;
    }
}
