/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyPatientsForm.java
 *
 * Created on 29 Ιαν 2009, 7:59:26 μμ
 */
/**
 *
 * @author User
 */
import java.util.*;
import javax.swing.DefaultListModel;


public class MyPatientsForm extends javax.swing.JInternalFrame {

    //Η κλάση αυτή περιέχη την φόρμα που είναι εφικτή
    //η διαχείριση του αρχείου των ασθενών
    Patients doctorsPatientsRecords;
    /** Creates new form MyPatientsForm */
    MainApplicationWindow parent;

    public MyPatientsForm(MainApplicationWindow p) {
        parent = p;
        doctorsPatientsRecords = p.getAllPatients();
        initComponents();
        mode = -1;
        doctorsPatientsRecords.ArrangePatients();
        UpdatePatientList();

    }

    public void UpdatePatientList() {
        //Η λίστα με όλους τους ασθενείς. Εμφανίζεται μόνο το όνοματεπώνυμο του ασθενούς
        //σε αυτήν
        DefaultListModel mdl = new DefaultListModel();

        Vector<Patient> pt = doctorsPatientsRecords.getPatients();
        Enumeration<Patient> e = pt.elements();
        while (e.hasMoreElements()) {
            Patient r = e.nextElement();
            String nameToShow = r.getSurname() + ", " + r.getName();
            mdl.addElement(nameToShow);
        }
        lstPatients.setModel(mdl);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPatients = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSurName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtInsurance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setTitle("Αρχείο Ασθενών");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstPatients.setName("lstPatients"); // NOI18N
        lstPatients.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPatientsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPatients);

        jLabel1.setText("Ασθενείς");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Όνομα");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Επώνυμο");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Διεύθυνση");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Τηλέφωνο (σταθερό)");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Τηλέφωνο (κινητό)");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Ασφαλιστικός Φορέας");
        jLabel7.setName("jLabel7"); // NOI18N

        txtSurName.setEnabled(false);
        txtSurName.setName("txtSurName"); // NOI18N
        txtSurName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurNameActionPerformed(evt);
            }
        });

        txtName.setEnabled(false);
        txtName.setName("txtName"); // NOI18N

        txtAddress.setEnabled(false);
        txtAddress.setName("txtAddress"); // NOI18N

        txtPhone.setEnabled(false);
        txtPhone.setName("txtPhone"); // NOI18N

        txtMobile.setEnabled(false);
        txtMobile.setName("txtMobile"); // NOI18N

        txtInsurance.setEnabled(false);
        txtInsurance.setName("txtInsurance"); // NOI18N
        txtInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceActionPerformed(evt);
            }
        });

        jButton1.setText("Νέος Ασθενής");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Μεταβολή Στοιχείων");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ιστορικό Ασθενούς");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Ημερομηνία Γέννησης");
        jLabel8.setName("jLabel8"); // NOI18N

        txtBirthday.setEnabled(false);
        txtBirthday.setName("txtBirthday"); // NOI18N
        txtBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthdayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSurName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddress, txtInsurance, txtMobile, txtName, txtPhone, txtSurName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (mode == -1) {
            //οταν ο χρήστης ζητήσει την εμφάνιση του ιστορικού
            //του επιλεγμένου ασθενή
            int maxelement = doctorsPatientsRecords.thePatients.size();
            int selectedElement = lstPatients.getSelectedIndex();
            if (selectedElement < 0 || selectedElement >= maxelement) {
                return;
            }
            HistoricalRecord newHistoricalRecord = new HistoricalRecord(doctorsPatientsRecords.getPatients().elementAt(selectedElement));
            parent.getMdiPanel().add(newHistoricalRecord);
            newHistoricalRecord.setVisible(true);
            this.setVisible(false);
        } else {
            //όταν ο χρήστης ακυρώση την εισαγωγή νέου ασθενούς
            //ή ακυρώσει την τροποποίηση των στοιχείων ενος ασθενή
            lstPatients.setEnabled(true);
            txtAddress.setEnabled(false);
            txtName.setEnabled(false);
            txtSurName.setEnabled(false);
            txtPhone.setEnabled(false);
            txtMobile.setEnabled(false);
            txtInsurance.setEnabled(false);
            txtBirthday.setEnabled(false);
            doctorsPatientsRecords.ArrangePatients();
            UpdatePatientList();
            lstPatients.setSelectedIndex(0);


        }

}//GEN-LAST:event_jButton3ActionPerformed

    private void txtSurNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtSurNameActionPerformed

    private void txtInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtInsuranceActionPerformed

    private void lstPatientsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPatientsValueChanged
        //Όταν ο χρήστης επιλέξει κάποιον ασθενή απο τη λίστα
        //εμφανίζονται τα αναλυτκά προσωπικά στοιχεία του ασθενούς
        //στην οθόνη
        Patient[] pt = null;
        pt = doctorsPatientsRecords.getPatients().toArray(new Patient[doctorsPatientsRecords.getPatients().size()]);
        int r = lstPatients.getSelectedIndex();
        if (r >= 0 && r < pt.length) {
            txtSurName.setText(pt[r].getSurname());
            txtName.setText(pt[r].getName());
            txtAddress.setText(pt[r].getAddress());
            txtPhone.setText(pt[r].getTelephone());
            txtMobile.setText(pt[r].getMobile());
            txtInsurance.setText(pt[r].getInsurance());
            txtBirthday.setText(pt[r].getBirthday());
        }
    }//GEN-LAST:event_lstPatientsValueChanged

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (mode == -1) {
            //Ο χρήστης ζητάει την εισαγωγή νέου ασθενούς
            //ενεργοποιούνται τα απαραίτητα στοιχεία
            //και αλλαζει η λειτουργία των κουμπιών
            lstPatients.setEnabled(false);
            txtAddress.setText("");
            txtName.setText("");
            txtSurName.setText("");
            txtPhone.setText("");
            txtMobile.setText("");
            txtInsurance.setText("");
            txtBirthday.setText("");
            txtAddress.setEnabled(true);
            txtName.setEnabled(true);
            txtSurName.setEnabled(true);
            txtPhone.setEnabled(true);
            txtMobile.setEnabled(true);
            txtInsurance.setEnabled(true);
            txtBirthday.setEnabled(true);

            jButton1.setText("Αποδοχή");
            jButton2.setVisible(false);
            jButton3.setText("Ακύρωση");

            mode = -2;
        } else if (mode == -2) {
            //Ο χρήστης ζητάει αποθήκευση των στοιχείων του νέου ασθενή που
            //εισήγαγε
            lstPatients.setEnabled(true);
            txtAddress.setEnabled(false);
            txtName.setEnabled(false);
            txtSurName.setEnabled(false);
            txtPhone.setEnabled(false);
            txtMobile.setEnabled(false);
            txtInsurance.setEnabled(false);
            txtBirthday.setEnabled(false);

            Patient pt = new Patient();
            pt.setBirthday(txtBirthday.getText());
            pt.setAddress(txtAddress.getText());
            pt.setInsurance(txtInsurance.getText());
            pt.setMobile(txtMobile.getText());
            pt.setSurname(txtSurName.getText());
            pt.setName(txtName.getText());
            pt.setTelephone(txtPhone.getText());
            doctorsPatientsRecords.getPatients().add(pt);

            lstPatients.setEnabled(true);
            doctorsPatientsRecords.ArrangePatients();
            UpdatePatientList();
            mode = -1;
            lstPatients.setSelectedIndex(lstPatients.getMaxSelectionIndex());

            jButton1.setText("Νέος Ασθενής");
            jButton2.setVisible(true);
            jButton2.setText("Μεταβολή Στοιχείων");
            jButton3.setText("Ιστορικό Ασθενούς");
        } else {
            //Ο χρήστης ζητάει αποθήκευση των στοιχείων του ασθενή που
            //τροποποίησε
            lstPatients.setEnabled(true);
            txtAddress.setEnabled(false);
            txtName.setEnabled(false);
            txtSurName.setEnabled(false);
            txtPhone.setEnabled(false);
            txtMobile.setEnabled(false);
            txtInsurance.setEnabled(false);
            txtBirthday.setEnabled(false);
            jButton1.setText("Νέος Ασθενής");

            doctorsPatientsRecords.getPatients().elementAt(mode).setBirthday(txtBirthday.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setAddress(txtAddress.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setInsurance(txtInsurance.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setMobile(txtMobile.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setSurname(txtSurName.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setName(txtName.getText());
            doctorsPatientsRecords.getPatients().elementAt(mode).setTelephone(txtPhone.getText());

            lstPatients.setEnabled(true);
            doctorsPatientsRecords.ArrangePatients();
            UpdatePatientList();
            lstPatients.setSelectedIndex(mode);
            mode = -1;
            jButton1.setText("Νέος Ασθενής");
            jButton2.setVisible(true);
            jButton2.setText("Μεταβολή Στοιχείων");
            jButton3.setText("Ιστορικό Ασθενούς");

        }
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthdayActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtBirthdayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (mode == -1) {
            mode = lstPatients.getSelectedIndex();
            lstPatients.setEnabled(false);
            txtAddress.setEnabled(true);
            txtName.setEnabled(true);
            txtSurName.setEnabled(true);
            txtPhone.setEnabled(true);
            txtMobile.setEnabled(true);
            txtInsurance.setEnabled(true);
            txtBirthday.setEnabled(true);

            jButton1.setText("Αποδοχή");
            jButton2.setText("Επαναφορά");
            jButton3.setText("Ακύρωση");


        } else {
            txtBirthday.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getBirthday());
            txtAddress.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getAddress());
            txtName.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getName());
            txtSurName.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getSurname());
            txtPhone.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getTelephone());
            txtMobile.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getMobile());
            txtInsurance.setText(doctorsPatientsRecords.getPatients().elementAt(mode).getInsurance());


        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
//        setComponentZOrder(this, 0);        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
  //      setComponentZOrder(this, 10);        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPatients;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtInsurance;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurName;
    // End of variables declaration//GEN-END:variables
    private int mode; //-1 -> Προβολή
    //-2 -> Νέος Ασθενής
    //ID -> Επεξεργασία της εγγραφής με Α/Α ΙD
}
