
import java.util.Calendar;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NumericalExamPanel.java
 *
 * Created on 30 Ιαν 2009, 5:16:26 μμ
 */

/**
 *
 * @author User
 */
public class NumericalExamPanel extends java.awt.Panel {
    private int id;
    public int getId() {
        return id;
    }
    //Αυτό το πάνελ μπαίνει μεσα σε tabs και χρησιμοποιείται για την εισαγωγή και
    //τροποποίηση αποτελεσμάτων εξετάσεων με αριθμητικά δεδομένα.
    public void setId(int newid) {
        id = newid;
        if(id < 0)
        {
            lblDayOfExam.setVisible(true);
            jLabel6.setVisible(true);
        }
    }

    /** Creates new form NumericalExamPanel */
    public NumericalExamPanel() {
        initComponents();
         jLabel6.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        txtMinNormal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaxNormal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblDayOfExam = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText("Τιμή Μέτρησης");
        jLabel1.setName("jLabel1"); // NOI18N

        txtResult.setName("txtResult"); // NOI18N
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });

        txtMinNormal.setName("txtMinNormal"); // NOI18N

        jLabel3.setText("Φυσικολογικά όρια");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Απο");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Έως");
        jLabel5.setName("jLabel5"); // NOI18N

        txtMaxNormal.setMinimumSize(new java.awt.Dimension(46, 20));
        txtMaxNormal.setName("txtMaxNormal"); // NOI18N
        txtMaxNormal.setPreferredSize(new java.awt.Dimension(46, 20));
        txtMaxNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxNormalActionPerformed(evt);
            }
        });

        jLabel6.setText("Ημερομηνία Εξέτασης");
        jLabel6.setName("jLabel6"); // NOI18N

        lblDayOfExam.setName("lblDayOfExam"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaxNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDayOfExam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtMaxNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDayOfExam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtResultActionPerformed

    private void txtMaxNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxNormalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtMaxNormalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDayOfExam;
    private javax.swing.JTextField txtMaxNormal;
    private javax.swing.JTextField txtMinNormal;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
    public boolean getExamResult(NumericalExamResult result)
    {
        //Η συνάρτηση αυτή επιστρέφει την νέα εγγραφή μετά τις εισαγωγές / αλλαγές.
        double resultValue, minNormal, maxNormal;
        try{
            resultValue = Double.parseDouble(txtResult.getText());
            minNormal = Double.parseDouble(txtMinNormal.getText());
            maxNormal = Double.parseDouble(txtMaxNormal.getText());
        }catch(Exception e)
        {
            return false;
        }
        result.setResult(resultValue);
        result.setMinNormalValue(minNormal);
        result.setMaxNormalValue(maxNormal);
        return true;

    }
    public void setExamResult(NumericalExamResult result)
    {
        //Η συνάρτηση αυτή εμφανίζει το αποτέλεσμα της εξέτασης στο χρήστη
        txtResult.setText(""+result.getResult());
        txtMinNormal.setText(""+result.getMinNormalValue());
        txtMaxNormal.setText(""+result.getMaxNormalValue());
        lblDayOfExam.setText(result.getExamDate().get(Calendar.DAY_OF_MONTH)+"/"
               +result.getExamDate().get(Calendar.MONTH)+"/"
               +result.getExamDate().get(Calendar.YEAR));

    }
}
