
import java.util.Calendar;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QualitiveExamPanel.java
 *
 * Created on 30 Ιαν 2009, 5:34:43 μμ
 */

/**
 *
 * @author User
 */

public class QualitiveExamPanel extends java.awt.Panel {
    //Αυτό το πάνελ μπαίνει μεσα σε tabs και χρησιμοποιείται για την εισαγωγή και
    //τροποποίηση αποτελεσμάτων εξετάσεων με ποιοτικά δεδομένα.
    /** Creates new form QualitiveExamPanel */
    private int id;
    public int getId() {
        return id;
    }

    public void setId(int newid) {
        id = newid;
         if(id < 0)
        {
            lblDayOfExam.setVisible(true);
            jLabel6.setVisible(true);
        }
    }
    public QualitiveExamPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        lblDayOfExam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Μετρηση");
        jLabel1.setName("jLabel1"); // NOI18N

        txtResult.setName("txtResult"); // NOI18N

        lblDayOfExam.setName("lblDayOfExam"); // NOI18N

        jLabel6.setText("Ημερομηνία Εξέτασης");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblDayOfExam, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDayOfExam, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDayOfExam;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
    public boolean getExamResult(QualitiveExamResult result)
    {
        if( txtResult.getText().length() < 2)
            return false;
        result.setResult(txtResult.getText());
        return true;
    }
     public void setExamResult(QualitiveExamResult result)
    {
        txtResult.setText(""+result.getResult());

        lblDayOfExam.setText(result.getExamDate().get(Calendar.DAY_OF_MONTH)+"/"
               +result.getExamDate().get(Calendar.MONTH)+"/"
               +result.getExamDate().get(Calendar.YEAR));

    }
}
